# Use the official Node.js 18.x base image
FROM node:18.x


# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project
COPY . .

# Build the React app
RUN npm run build

# Set the command to start the app
CMD [ "npm", "start" ]
